# Generated by Django 5.2.4 on 2025-09-06 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('duration_min', models.PositiveIntegerField(default=30)),
                ('priority', models.IntegerField(default=3)),
                ('desired_time', models.CharField(choices=[('early_morning', 'Early morning'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night'), ('any', 'Any')], default='any', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('start_hhmm', models.CharField(max_length=5)),
                ('end_hhmm', models.CharField(max_length=5)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.dayplan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.task')),
            ],
            options={
                'ordering': ['start_hhmm', 'order'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.taskgroup'),
        ),
    ]
