# Generated by Django 5.2.4 on 2025-09-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recur_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='recur_monthday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recur_weekdays',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.CharField(choices=[('none', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays (Mon–Fri)'), ('weekends', 'Weekends (Sat–Sun)'), ('monthly', 'Monthly (by day-of-month)'), ('custom', 'Custom RRULE-ish')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='rrule_text',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='task',
            name='skip_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
