# Generated by Django 5.2.4 on 2025-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_end_date_task_recur_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
