# Generated by Django 5.2.4 on 2025-09-08 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_deadline_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='description_type',
            field=models.CharField(choices=[('none', 'None'), ('text', 'Plain text'), ('check', 'Checklist')], default='none', max_length=8),
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='planner.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
