# Generated by Django 5.2.4 on 2025-09-08 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_task_description_text_task_description_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_drawings/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='planner.task')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
