# Generated by Django 5.2.4 on 2025-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_taskdrawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description_type',
            field=models.CharField(choices=[('none', 'None'), ('text', 'Plain text'), ('check', 'Checklist'), ('scribble', 'Scribbles')], default='none', max_length=8),
        ),
    ]
