# Generated by Django 5.2.4 on 2025-09-08 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_task_description_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description_type',
            field=models.CharField(choices=[('none', 'None'), ('text', 'Plain text'), ('check', 'Checklist'), ('scribble', 'Scribbles'), ('attachments', 'Attachments')], default='none', max_length=15),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'heic', 'heif', 'm4a', 'mp3', 'wav', 'aac', 'ogg', 'mp4', 'mov', 'webm'])])),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=80)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.task')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
